### ISSUE TITLE
Same csv header value may corrupt the output.

### ISSUE THREAD

**Issue by takirala** [ctsit/nacculator#10]
We are parsing the input csv in to a python dictionary and if two headers have the same name, then the second value of the header will over write the first value and it will result in an error.

For example, C2 and C1 have a field called fu_npsylan. If there is data in both these forms, then nacculator may not work as expected.

**Comment by ufl-taeber** [comment]
I don't this is a general issue since REDCap requires field names to be unique within a project regardless of which form. It may have once been valid for the specific case of C1 and C2, but is it still an issue since C1 is no longer used. Am I correct, @KevinHanson @naomidb ?

**Comment by KevinHanson** [comment]
C1 as a form is no longer used and the newer versions of NACCulator do not use the C1 form. This issue is no longer applicable so closing. Thank you for reporting the issue.
