### ISSUE TITLE
Skip Z1 form if not present in REDCap project

### ISSUE THREAD

**Issue by s-emerson** [ctsit/nacculator#108]
Some ADRCs do not have the Z1 form in their REDCap projects (the form was deprecated some years ago and is not used today). Currently, nacculator needs there to be Z1 fields like "z1_form_complete" within the csv data file, even if the value is blank, in order to avoid raising a KeyError. 
In order to solve this issue, we need to either add a flag, filter, configuration, or some internal logic so that nacculator knows to skip the Z1 form fields altogether if they are not present in the data file.

It might be a good idea to include other old forms like C1/C1S in this feature.

**Comment by vsmalladi** [comment]
Yes just hit this issue when trying to use it for our project which didn't fill this form out.

**Comment by s-emerson** [comment]
Addressed with pull request https://github.com/ctsit/nacculator/pull/110
