### ISSUE TITLE
run_filters.py isn't included in pip install

### ISSUE THREAD

**Issue by ufl-taeber** [ctsit/nacculator#109]
After installing nacculator via pip, there is no way to run the `run_filters.py` script as per the [Example Workflow](https://github.com/ctsit/nacculator#example-workflow) instructions.

**Comment by ufl-taeber** [comment]
To clarify, `run_filters.py` needs to be moved to the `nacc` folder and included in the `setup.py` as a command-line tool.

**Comment by s-emerson** [comment]
Addressed with pull request 110: https://github.com/ctsit/nacculator/pull/110
