### ISSUE TITLE
Install error from current README "python3 -m pip install git+https://github.com/ctsit/cappy.git@2.0.0#egg=cappy-2.0.0"

### ISSUE THREAD

**Issue by senrabc** [ctsit/nacculator#124]
Console dump:

python3 -m pip install git+https://github.com/ctsit/cappy.git@2.0.0#egg=cappy-2.0.0
Collecting cappy-2.0.0
  Cloning https://github.com/ctsit/cappy.git (to revision 2.0.0) to /private/var/folders/q_/01yhg7v96457h0d15qc7ww1m0000gn/T/pip-install-7jndrbyw/cappy-2-0-0_263158473d8e49799a7cc4afa8e8aea1
  Running command git clone -q https://github.com/ctsit/cappy.git /private/var/folders/q_/01yhg7v96457h0d15qc7ww1m0000gn/T/pip-install-7jndrbyw/cappy-2-0-0_263158473d8e49799a7cc4afa8e8aea1
  Running command git checkout -q 857729e81eca70fae5cb411f9092916d23876d1a
  WARNING: Generating metadata for package cappy-2.0.0 produced metadata for project name cappy. Fix your #egg=cappy-2.0.0 fragments.
WARNING: Discarding git+https://github.com/ctsit/cappy.git@2.0.0#egg=cappy-2.0.0. Requested cappy from git+https://github.com/ctsit/cappy.git@2.0.0#egg=cappy-2.0.0 has inconsistent name: filename has 'cappy-2-0-0', but metadata has 'cappy'
ERROR: Could not find a version that satisfies the requirement cappy-2-0-0 (unavailable) (from versions: none)
ERROR: No matching distribution found for cappy-2-0-0 (unavailable)

**Comment by s-emerson** [comment]
command has been corrected to:
python3 -m pip install git+https://github.com/ctsit/cappy.git@2.0.0

verified that this works to install the most recent version of nacculator for mel while testing my pull request.
