### ISSUE TITLE
Nacculator erroring and stopping

### ISSUE THREAD

**Issue by PFWhite** [ctsit/nacculator#13]
Nacculator needs to handle errors better.

Currently it will except and then stop processing. It should instead do all that it can, and generate two files. One will be the output that it could handle, and the other will be an error log that shows what it could not do and why

**Comment by KevinHanson** [comment]
In the latest release of nacculator today Tarun inserted a skipping error handler and currently the output only goes to the console but with the logic in place it shouldn't be hard to output to a file. Thanks for logging this issue.

Kind Regards,

Kevin Hanson

**Comment by ufl-taeber** [comment]
Closing as this seems long since completed.
