### ISSUE TITLE
Update readme for updatefield filter with example

### ISSUE THREAD

**Issue by KevinHanson** [ctsit/nacculator#23]
PYTHONPATH=. ./nacc/redcap2nacc.py -f updateField -file cleaned-ptids.csv > center-id-updated.csv

**Comment by ufl-taeber** [comment]
It looks like `updateField` is listed in the README. There is also an example of how to run filters (specifically `cleanPtid`), but since it's the same syntax as `updateField`, I'm going to mark this as done.
