### ISSUE TITLE
New Filter For 3 date fields with 88/88/8888

### ISSUE THREAD

**Issue by DevMattM** [ctsit/nacculator#27]
There is a form (I forget which right now) that has three date fields - one for day, month, year. Clinicians frequently put 88/88/8888 or 88/88/88 in the day field which is incorrect. This should be split into 88 for day, 88 for month, and 8888 for year. At the same time, 88 for year should be fixed to 8888

**Comment by DevMattM** [comment]
C1S form

**Comment by ufl-taeber** [comment]
@naomidb and @KevinHanson , since C1S is deprecated, is this still an issue?

**Comment by naomidb** [comment]
Yes, we want to be able to do full reuploads of all visits so NACCulator needs to be functional with C1S.

**Comment by KevinHanson** [comment]
We performed a full re-upload of all data and corrected this issue in a recent release.
