### ISSUE TITLE
fu_otherneur field needs to be renamed to match NACC Dictionary

### ISSUE THREAD

**Issue by DevMattM** [ctsit/nacculator#28]
The Redcap data has a FVP field called fu_otherneur. NACC is expecting a field called fu_othneur. 

Should be: fu_othneur

https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/fvp_ded.pdf

**Comment by DevMattM** [comment]
This has been handled via config file found in release 0.3.0

**Comment by ufl-taeber** [comment]
I want to reopen this. The real issue wasn't that the field needed to be renamed, it's that the mapping in the `fvp/builder.py` file needs to be updated. Once that is done, nacculator will correctly handle this field and `fu_othneurx` without needing to use the `fixHeaders` filter.

**Comment by KevinHanson** [comment]
Right so this is a field rename in REDCap data dictionary then but I never pulled the trigger because of the destructive change. If we sat down to plan it out we could find away to make the 4-5 changes to eliminate the fix headers filter.

**Comment by naomidb** [comment]
Ultimately the filter fix is the most elegant solution we have for now if we want NACCulator to be useful for the maximum number of people, so we will stick to that.
