### ISSUE TITLE
Incorrect unknown value '999' for Form A2 INEDUC in uds3/fvp/forms.py

### ISSUE THREAD

**Issue by ldnicolasmay** [ctsit/nacculator#51]
I believe the unknown value for Form A2 field INEDUC should be '99' instead of '999'.

Line 62 in uds3/fvp/forms.py current:
`self.fields['INEDUC'] = nacc.uds3.Field(name='INEDUC', typename='Num', position=(315, 316), length=2, inclusive_range=(0, 36), allowable_values=['999'], blanks=['Blank if Question 3 NEWINF = 0 (No)'])`

Possible correction:
`self.fields['INEDUC'] = nacc.uds3.Field(name='INEDUC', typename='Num', position=(315, 316), length=2, inclusive_range=(0, 36), allowable_values=['99'], blanks=['Blank if Question 3 NEWINF = 0 (No)'])`

Thanks!

**Comment by ufl-taeber** [comment]
I agree.

The [UDS 3.0 FVP Data Element Dictionary](https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/fvp_ded.pdf) states that the length of the `INEDUC` field is 2, so `999` is invalid. Looking at the [IVP DED](https://www.alz.washington.edu/NONMEMBER/UDS/DOCS/VER3/ivp_ded.pdf), it states `99` should be used.
